# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  projectPath: 'Source/Web'
  coreCliVersion: 3.1.300


steps:

- task: DotNetCoreInstaller@1
  displayName: 'Installing NetCore version $(coreCliVersion)...'
  inputs:
    version: $(coreCliVersion)
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration Release'
    workingDirectory: '$(projectPath)/**.csproj'
